### ISSUE TITLE
Add support for Angular 7 and 8 (and 9?)

### ISSUE THREAD

**Issue by jonathanvhive** [TGFTech/angular2parse#5]
Hi,
Can you please add support for modern Angular versions? package.json defines Angular 6 as the newest supported version.
angular2parse is a dependency for other project which already support newer angular versions, but npm install shows a warning about angular2parse because of this issue.
Thanks

**Comment by jonathanvhive** [comment]
@eitanfr thanks. Do you mind bumping to 1.0.9 and publishing to NPM? That way Cesium will the new version automatically (they're using ^1.0.8).

**Comment by eitanfr** [comment]
Sure,
we just need to transfer the NPM package to our user first.
working on it :)
